### ISSUE TITLE
Exposure Notification Api Not Enabled on Android

### ISSUE THREAD

**Issue by sinh-bui-vgh** [CovidShield/mobile#104]
I have tried to run the code in android phone but got the red toasts saying the exposure notification is off. While clicking on the "Turn on exposure notification" button the app was navigated to the App Info view, where there are no options for turning on the exposure notification.

I have tried going to google play services app setting on the phone and manually turned on the exposure notification API, but when running the app the exposure notification client is still not enabled.

Please help, is there any part of the code that I need to change to get it to work? Or is there any step for config that I missed?

**Comment by CodeSchneider** [comment]
I'm having the same issue. For iOS as well.

**Comment by henrytao-me** [comment]
Close this and link to https://github.com/CovidShield/mobile/issues/115
