### ISSUE TITLE
Can't turn on Exposure notifications or Bluetooth

### ISSUE THREAD

**Issue by CodeSchneider** [CovidShield/mobile#114]
I'm seeing an issue with production iOS and Android builds. `TEST_MODE` is set to false, and `MOCK_SERVER` is set to false. I'm running on real hardware. iOS version is 13.5, and Android is version 9, and google play services is the latest, as suggested in your readme. The app is talking to a deployed instance of CovidShield server, which appears to be functioning. This is what I'm seeing:

When getting to the app's home page, COVID Shield is in the "OFF" state. Both the Exposure notifications and Bluetooth tiles are red. When I try to turn on either of those two settings, I'm redirected to the app's settings page, but no permissions are granted, and both tiles remain red. 

Enabling Push notifications works, however.

Below are screenshots of the experience on iOS and Android. This might be related to an [issue #104 raised yesterday](https://github.com/CovidShield/mobile/issues/104).

Android pics:

![image](https://user-images.githubusercontent.com/7592718/84420040-75c71d80-abe7-11ea-9f9e-fb08bd4a6fdd.png)

![image](https://user-images.githubusercontent.com/7592718/84420058-7a8bd180-abe7-11ea-89d8-baab921418f1.png)

![image](https://user-images.githubusercontent.com/7592718/84420072-7d86c200-abe7-11ea-936d-deaf97839205.png)

iOS pics:

![image](https://user-images.githubusercontent.com/7592718/84420091-82e40c80-abe7-11ea-88fb-12122a4096b4.png)

![image](https://user-images.githubusercontent.com/7592718/84420100-86779380-abe7-11ea-8295-af887c1a7b38.png)

![image](https://user-images.githubusercontent.com/7592718/84420109-89728400-abe7-11ea-8a59-a1d2a1674b38.png)

Any ideas?

**Comment by jason-whelan-vgh** [comment]
On the iOS side, you need a provisioning profile with the Exposure notification entitlement. You then need to update the CovidShield.entitlements file with the correct entitlements. Then when you run the app and go through onboarding you will get prompted to enable exposure notifications.

**Comment by CodeSchneider** [comment]
Thanks for response, @jason-whelan-vgh, you are right. For others reading this, to get provisioning profile with Exposure notification entitlement go [here](https://developer.apple.com/contact/request/exposure-notification-entitlement)

**Comment by henrytao-me** [comment]
FYI, on Android, it needs APPLICATION_ID to be whitelisted by Google. You can also use APPLICATION_ID from Google Sample app for testing `com.google.android.apps.exposurenotification` https://github.com/google/exposure-notifications-android/blob/master/app/build.gradle#L33. 

However, the native bridge is missing some code to show consent dialog. PR is up soon https://github.com/CovidShield/mobile/issues/115.
