### ISSUE TITLE
Bluetooth and Exposure Notification should be checked separately

### ISSUE THREAD

**Issue by henrytao-me** [CovidShield/mobile#125]
## What

Bluetooth and Exposure Notification should be checked separately in app

## Context

About Bluetooth and Exposure Notification:
- They are two separate permission / option. You can still turn on EN but turn off Bluetooth.
- If EN is ON but Bluetooth is OFF, the framework on Android automatically shows a notification asking user to turn it on. User can dismiss the notification without turning it on. 
- If bluetooth is OFF and user dismisses the notification, it is most likely that EN won't work properly.
- The 1st screenshot shows both EN is OFF and Bluetooth is OFF but my bluetooth is actually ON.
- The 2nd screenshot shows EN is ON but bluetooth is OFF but in the app, there is no UI saying it is off and needs to turn on.

<img src="https://user-images.githubusercontent.com/5274722/84895508-6a08aa80-b070-11ea-894f-69452570bf28.png" width="240" />

<img src="https://user-images.githubusercontent.com/5274722/84895511-6bd26e00-b070-11ea-9205-d332d26747bb.png" width="240" />

**Comment by ChrisDryden** [comment]
I'm working on this in the cds-sns repo, also working on adding the correct deep-links to the page to enable bluetooth.

**Comment by ChrisDryden** [comment]
added some notes here https://github.com/cds-snc/covid-shield-mobile/issues/78

**Comment by ChrisDryden** [comment]
Would you be okay with me implementing this with this library? It has functionality to be able to see it bluetooth is enabled and includes a link to the bluetooth settings page. https://github.com/c19354837/react-native-system-setting

**Comment by ChrisDryden** [comment]
It appears that more functionality is needed in the android status check. Currently it appears that the bluetooth status is not checked currently for android and is only checked for iOS.

**Comment by ChrisDryden** [comment]
This PR uses an additional library that can get the status of whether bluetooth is enabled and actually allows you to enable it from the app in Android. In iOS it appears that you are actually not able to access the bluetooth settings from an app and will be blocked from the app store if you attempt to do so so this is the fix for that too.

**Comment by henrytao-me** [comment]
Hi @ChrisDryden ,

I was discussing with my team few days ago and we think it makes more sense for user to not care about bluetooth if using exposure notification (EN). That means: 
- The turn on bluetooth UI should be removed. 
- Android bridge for EN should also check bluetooth status and returns same payload as iOS. 
- When turn on EN, Android should turn on bluetooth at the same time. 

So, it is a bug / feature needed to implement on Android. I will close this issue and open another one.

**Comment by timarney** [comment]
Re: EN + Blue Tooth 

**Note: I haven't gotten fully up to speed yet on how the EN api works**

**Scenarios - EN entitlements**

==========================
So we're all on the same page - without needing to read all the docs

If this is available somewhere already would love to see it.

1) From the APP when a user turns on EN does that enable EN + Bluetooth?
2) After EN is on what happens later if the user separately turns off Bluetooth (Still works for push notifications and already collected data but won't collect anymore?)
3) Airplane mode - what happens?


**When we're saying turn on EN for iOS that is here**

<img width="300" src="https://user-images.githubusercontent.com/62242/85223426-1f00d700-b391-11ea-8210-3e99551a512c.jpg">

**Comment by henrytao-me** [comment]
I was playing round with existing app like this https://www.immuni.italia.it/download.html. Look like: 

- On Android: 
+ Turn on EN will automatically turn on bluetooth. It is not because of the framework support that it is because Android can turn on bluetooth programmatically. 

- On iOS: the flow is more complex
+ If bluetooth is turn OFF while EN is ON, the app shows inactive and ask user to turn on bluetooth manually. 
+ I don't have enough information to answer 2) and 3). So, we might need to ask Apple team, I guess. 

cc @gavrix if you know iOS answer. 🙇
