### ISSUE TITLE
How does COVID Alert compare with COVID Shield?

### ISSUE THREAD

**Issue by mgifford** [CovidShield/mobile#131]
It sounds like this is basically the same software with a different name:
https://nationalpost.com/pmn/health-pmn/canadas-shopify-blackberry-develop-covid-19-contact-tracing-app-with-local-governments

Is this the same tool?  If so, when will it be available through the Google/Apple stores?

**Comment by jroo** [comment]
Hi Mike. Yeah, what we're working on at [CDS](https://github.com/cds-snc/) is a fork of COVID Shield and our repos will be open in the next few days. The app should be available in the app stores in the coming weeks.

**Comment by timarney** [comment]
@mgifford https://github.com/cds-snc/covid-shield-mobile

At some point we'll document the changes -- after we get bugs etc... sorted out.
