### ISSUE TITLE
F-Droid installation

### ISSUE THREAD

**Issue by weatherman2095** [CovidShield/mobile#136]
Given the privacy-respecting principles underlined within the whitepaper about [Privacy-Preserving Contact Tracing](https://www.apple.com/covid19/contacttracing) one would imagine that being able to install this application in a manner which is similarly respectful of one's privacy (unlike Google Play) might be desirable.

In order to achieve such a result, one could use the [F-Droid software repository](https://f-droid.org/), which has a reasonably good reputation regarding these matters and reasonable guidelines for developers.

**Comment by henrytao-me** [comment]
The app has to be approved by Google Play team. It uses Google and Apple Exposure Notification framework. So, I would prefer to keep the app in one place as the source of truth to prevent confusion. Not everyone is a tech savvy to use different repositories.
