### ISSUE TITLE
Keyboard not dismissed after typing in code

### ISSUE THREAD

**Issue by smcmurtry** [CovidShield/mobile#141]
When you finish typing in the 8th digit of the code, the "submit code" button becomes enabled. When you click the button, the keyboard disappears, but nothing happens. You need to click the button a second time.

![Image from iOS](https://user-images.githubusercontent.com/5498428/85345375-8d3bbb80-b4af-11ea-8fd4-ce06b2fb8fb0.png)

![Image from iOS (1)](https://user-images.githubusercontent.com/5498428/85345389-9462c980-b4af-11ea-9797-e16a6b0c261b.png)

**Comment by henrytao-me** [comment]
PR is up 🙇

**Comment by smcmurtry** [comment]
Thank you @henrytao-me!!
