### ISSUE TITLE
Enter code -> submit -> don't agree and close shows wrong screen 

### ISSUE THREAD

**Issue by timarney** [CovidShield/mobile#145]
After submitting a successful code if the user doesn't agree on the next screen and instead closes the menu via sliding the menu(s) / pages down or via the cancel button the wrong page is displayed

Steps to reproduce

Enter a code + submit
Either slide down the menu or press cancel

![85399584-0e816580-b525-11ea-9ff7-efb1e65176b1](https://user-images.githubusercontent.com/62242/85405006-c9156600-b52d-11ea-9b4a-e26f22517229.gif)

The "in behind page" is the Daily share content.

https://github.com/cds-snc/covid-shield-mobile/issues/93

**Comment by henrytao-me** [comment]
This is the correct behavior. What happens is that the `OneTimeCode` can only be claimed once. After entering the code, the app sends to server immediately to validate and generate private / public key for next step. When user is on consent screen, they have option to cancel it which should not navigate user back to OneTimeCode screen again. If user decides to accept the consent later, they won't be asked for the code again. However, there are some action items we could do here https://github.com/CovidShield/mobile/issues/149
