### ISSUE TITLE
Exposed status is never checked properly

### ISSUE THREAD

**Issue by henrytao-me** [CovidShield/mobile#193]
## What?

The app fetches server for every 15 mins including today keys request and update `lastChecked`. The problem is that the serve refuses to return today keys. As the result, the app will always fetch today while it supposes to fetch yesterday key. Therefore, exposed status will never shown up.

```ts
    const finalize = async (status: Partial<ExposureStatus> = {}) => {
      const timestamp = new Date().getTime();
      this.exposureStatus.append({...status, lastChecked: timestamp});
    };
```

## Suggestion
- Store `lastChecked` as latest period that server return keys file (excluding `error while downloading key file: [Error: null]`) instead of current check timestamp.

**Comment by gavrix** [comment]
The fix should be: instead of storing timestamp of last check store the last period we got keys for successfully.
