### ISSUE TITLE
Wrong Messages icon appears on Android share screen

### ISSUE THREAD

**Issue by kpeatt** [CovidShield/mobile#63]
The wrong Messages icon is being used on Android share screen

![image](https://user-images.githubusercontent.com/447683/83164073-c9ab1000-a0d9-11ea-8e49-8788b1642acd.png)

**Comment by AdamWhitcroft** [comment]
Here's the Android messages icon.

<img width="360" alt="android-messages" src="https://user-images.githubusercontent.com/861526/83164317-155db980-a0da-11ea-9b6a-d6df1a3e26d8.png">

As part of this, we should like update IG to match:

<img width="360" alt="android-ig" src="https://user-images.githubusercontent.com/861526/83164316-14c52300-a0da-11ea-9ef9-6c12db352835.png">
