### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by AdamWhitcroft** [CovidShield/mobile#67]
Offer a dark mode version of the app (images/links wip)

**Comment by owencraston** [comment]
RN 062 added [ppearance.getColorScheme()](ppearance.getColorScheme())

**Comment by owencraston** [comment]
Dark mode designs: https://www.figma.com/file/xKtKYxl28Drx0nTL4qznla/COVID-Shield---Client-App?node-id=1808%3A0

**Comment by AdamWhitcroft** [comment]
I've added some callouts to each of the screens linked above with changes.
