### ISSUE TITLE
BottomSheet cannot scroll in Android release build

### ISSUE THREAD

**Issue by henrytao-me** [CovidShield/mobile#80]
## Steps to reproduce:
- Build Android release build with any keystore.
- Pass onboarding screen.
- Open BottomSheet.
- Expect BottomSheet cannot scroll.

**Comment by sbearben** [comment]
Does this refer to the bottomSheet content? If so this would be solved by PR here: https://github.com/CovidShield/mobile/pull/64/files#diff-fd838fc0404393664e941314a16c6240R111

**Comment by henrytao-me** [comment]
Yes, it does. Thanks @sbearben

**Comment by jordanAtShopify** [comment]
Fixed
