### ISSUE TITLE
[Bug] Back button is not using localized string in Onboarding

### ISSUE THREAD

**Issue by kpeatt** [CovidShield/mobile#83]
![image](https://user-images.githubusercontent.com/447683/83427652-0d19bd00-a3ff-11ea-8349-c5fb8cf96200.png)

As shown here, the 'ActionBack' button is not respecting the localized string in the onboarding tutorial.

**Expected:** Button says `Précédent`

**Comment by kpeatt** [comment]
Looks good on Android too.

**Comment by jordanAtShopify** [comment]
Fixed
